Update test-gh-actions.yml

diff --git a/.github/workflows/test-gh-actions.yml b/.github/workflows/test-gh-actions.yml
--- a/.github/workflows/test-gh-actions.yml
+++ b/.github/workflows/test-gh-actions.yml
@@ -44,9 +44,14 @@ jobs:
     needs: [job1, job2]
   
     steps:
-      - uses: actions/checkout@v4
-  
-      - name: Log results
+      - name: Evaluate results
         run: |
-          echo "Resultado job1: ${{ needs.job1.result }}"
-          echo "Resultado job2: ${{ needs.job2.result }}"
+          echo "job1: ${{ needs.job1.result }}"
+          echo "job2: ${{ needs.job2.result }}"
+  
+          if [[ "${{ needs.job1.result }}" == "failure" && "${{ needs.job2.result }}" == "failure" ]]; then
+            echo "Ambos jobs fallaron → pipeline FAIL"
+            exit 1
+          else
+            echo "Al menos uno tuvo success → pipeline SUCCESS"
+          fi
